---
author: 'Ian Fayorsey'
date: 'November 2018'
division: 'Statistics'
advisor: 'Advisor Nicholas Horton'
department: 'Mathematics and Statistics'
title: 'My Comprehensive Evaluation'
abstract: >
  `r paste(readLines('abstract.Rmd'), collapse = '\n')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is # needed on the line after the >.
acknowledgements: >
  I would like extend my graditude to several people. Professor Nick Horton, and Professor Amy Wagaman, for their guidance, and encouragement over the past 4 years at Amherst. Since declaring my major sophomore year, Professor Horton has been my advisor and confidant, helping me through any and all adversities. During challenging times, Professor Wagaman helped me remain confident and hopeful. My academic development from probability to data analysis is a result of your unwavering support. To the entire statistics department, thank you for equipping me with the skills and thought process to tackle future problems in a formulaic and interpretable manner. Finally, to my mother, father, and sister - for helping me realize my potential and become the man I am today.
bibliography: bib/thesis.bib
# Modify your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
output: 
  acstats::amherst_thesis:
    toc: true
lot: true
lof: true
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 12 and 13 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting PDF file enclose it in a block like this.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the acstats package is
# installed and loaded. This acstats package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(acstats)){
  library(devtools)
  devtools::install_github("Amherst-Statistics/acstats")
}
library(acstats)
```

<!--
This is the way to split your thesis into chapters and then include each of the chapters seperately.  You can Knit the Rmd files corresponding to each chapter individually and then put them all back together by Knit-ing this document.

This is an R chunk and chap0.Rmd refers to the Introductory chapter.  Feel free to name this file as something else, but don't forget to change the argument to in `child = ` below!
-->

```{r intro, child = 'chap0.Rmd'}
```

<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

```{r chapter1, child = 'CopyOfchap1.Rmd', cache=TRUE}
```


<!--
Immediately below is the chunk for Chapter 2.
--> 

```{r chapter2, child = 'CopyOfchap2.Rmd'}
```

```{r chapter3, child = 'CopyOfchap3.Rmd', cache=TRUE}
```


<!--
Add other chunks here for other chapters in your thesis.  Note that if you use the `child =` parameter, you can't include anything else in your chunk.
-->

```{r conclusion, child = 'conclusion.Rmd'}
```

<!--
The bib chunk below must go last in this document according to how R Markdown renders.  More info is at http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
-->

```{r bib, child = 'bibliography.Rmd'}
```

